# SPDX-License-Identifier: BSD-3-Clause
#
# This file is part of the Avular Origin One project.
#
# Based on code from the WheeledLab project (https://github.com/NVlabs/wheeledlab)
# Copyright (c) 2025–2027, The Wheeled Lab Project Developers.
#
# Modified by the Avulab Project Developers (5ARIP10), 2025–2025.
# Modifications include: New Author Names


[package]

# Semantic Versioning is used: https://semver.org/
version = "0.1.0"

# Description
category = "isaaclab"
readme  = "README.md"

title = "AvuLab"
author = "AvuLab Project Developers"
maintainer = "AvuLab Project Developers"
description= "Isaac Lab for Wheeled Robots"
repository = "https://github.com/kgulikers/Team_internship_5ARIP10.git"
keywords = ["extension", "isaaclab"]

[dependencies]
"isaaclab" = {}
"isaaclab_assets" = {}
"isaclab_mimic" = {}
"isaaclab_rl" = {}
"isaaclab_tasks" = {}
# NOTE: Add additional dependencies here

[[python.module]]
name = "avulab_tasks"

[isaaclab_settings]
# TODO: Uncomment and list any apt dependencies here.
#       If none, leave it commented out.
# apt_deps = ["example_package"]
# TODO: Uncomment and provide path to a ros_ws
#       with rosdeps to be installed. If none,
#       leave it commented out.
# ros_ws = "path/from/extension_root/to/ros_ws"
